type User {
  id: ID!
  username: String!
  avatar: String
  status: UserStatus!
  events: [Event!]!
}

input CreateUserInput {
  username: String!
  avatar: String
  password: String
}

enum UserStatus {
  ONLINE
  OFFLINE
  AWAY
}

type Query {
  user(id: Int!): User
  users(keyword: String!): [User]!
}

type Mutation {
  createUser(createUserInput: CreateUserInput!): User!
  removeUser(id: String!): User
}
